---
language: python
python:
  - "3.6"

# Install python packages for ansible and linters.
install:
  - "pip install -r requirements.txt"

# Execute linting unit tests before running the main programs.
# If any of these tasks fail, the entire build fails immediately.
before_script:
  - "mkdir outputs/"
  - "make lint"
  - "make unit"

# Run the script four times, using three explicit verbosities and one
# default setting just to make sure it doesn't barf exceptions.
script:
  - "make run"
...
